export interface Driver {
  id: string;
  name: string;
  number: string;
  nationality: string;
  teamId: string;
  image?: string;
}

export interface Team {
  id: string;
  name: string;
  color: string;
  car?: string;
  logo?: string;
  class?: string;
}

export interface Race {
  id: string;
  name: string;
  location: string;
  date: string;
  circuit: string;
  status: 'upcoming' | 'completed' | 'cancelled';
  winner?: string;
}

export interface StandingItem {
  position: number;
  name: string;
  points: number;
  team?: string;
  extra?: string;
}

export interface CategoryStandings {
  drivers?: StandingItem[];
  constructors?: StandingItem[];
  teams?: StandingItem[];
}

export interface Category {
  id: string;
  name: string;
  fullName: string;
  description: string;
  longDescription: string;
  icon: string;
  teams: Team[];
  drivers: Driver[];
  calendar: Race[];
  standings?: CategoryStandings;
}

export const MOTORSPORT_DATA: Category[] = [
  {
    id: 'f1',
    name: 'F1',
    fullName: 'Formula 1',
    description: 'A categoria máxima do automobilismo mundial, com os carros de assento único mais rápidos do planeta.',
    longDescription: 'A Fórmula 1 é o auge do automobilismo, regulada pela FIA. O campeonato consiste em uma série de corridas, conhecidas como Grandes Prêmios, realizadas em circuitos de rua e autódromos permanentes. Os carros são os mais rápidos do mundo em circuitos mistos, graças a uma aerodinâmica extremamente avançada e motores híbridos V6 turbo de 1.6 litros. O sistema de pontuação premia os 10 primeiros colocados (25, 18, 15, 12, 10, 8, 6, 4, 2, 1), com um ponto extra para a volta mais rápida se o piloto terminar no top 10. Em 2026, novas regras de motores e aerodinâmica entram em vigor, focando em combustíveis 100% sustentáveis e maior potência elétrica.',
    icon: 'Trophy',
    teams: [
      { id: 'mercedes', name: 'Mercedes-AMG PETRONAS', color: '#00D2BE', car: 'W17' },
      { id: 'ferrari', name: 'Scuderia Ferrari HP', color: '#DC0000', car: 'SF-26' },
      { id: 'mclaren', name: 'McLaren Formula 1', color: '#FF8700', car: 'MCL40' },
      { id: 'haas', name: 'MoneyGram Haas F1 Team', color: '#FFFFFF', car: 'VF-26' },
      { id: 'alpine', name: 'BWT Alpine F1 Team', color: '#0093CC', car: 'A526' },
      { id: 'redbull', name: 'Oracle Red Bull Racing', color: '#0600EF', car: 'RB22' },
      { id: 'rb', name: 'Visa Cash App RB', color: '#6692FF', car: 'VCARB 03' },
      { id: 'audi', name: 'Audi F1 Team', color: '#F50537', car: 'Audi F1' },
      { id: 'williams', name: 'Williams Racing', color: '#005AFF', car: 'FW48' },
      { id: 'cadillac', name: 'Cadillac Racing', color: '#555555', car: 'Cadillac F1' },
      { id: 'astonmartin', name: 'Aston Martin Aramco', color: '#006F62', car: 'AMR26' },
    ],
    drivers: [
      { id: 'norris', name: 'Lando Norris', number: '1', nationality: 'Reino Unido', teamId: 'mclaren' },
      { id: 'piastri', name: 'Oscar Piastri', number: '81', nationality: 'Austrália', teamId: 'mclaren' },
      { id: 'verstappen', name: 'Max Verstappen', number: '3', nationality: 'Países Baixos', teamId: 'redbull' },
      { id: 'hadjar', name: 'Isack Hadjar', number: '6', nationality: 'França', teamId: 'redbull' },
      { id: 'leclerc', name: 'Charles Leclerc', number: '16', nationality: 'Mônaco', teamId: 'ferrari' },
      { id: 'hamilton', name: 'Lewis Hamilton', number: '44', nationality: 'Reino Unido', teamId: 'ferrari' },
      { id: 'russell', name: 'George Russell', number: '63', nationality: 'Reino Unido', teamId: 'mercedes' },
      { id: 'antonelli', name: 'Kimi Antonelli', number: '12', nationality: 'Itália', teamId: 'mercedes' },
      { id: 'alonso', name: 'Fernando Alonso', number: '14', nationality: 'Espanha', teamId: 'astonmartin' },
      { id: 'stroll', name: 'Lance Stroll', number: '18', nationality: 'Canadá', teamId: 'astonmartin' },
      { id: 'gasly', name: 'Pierre Gasly', number: '10', nationality: 'França', teamId: 'alpine' },
      { id: 'colapinto', name: 'Franco Colapinto', number: '43', nationality: 'Argentina', teamId: 'alpine' },
      { id: 'ocon', name: 'Esteban Ocon', number: '31', nationality: 'França', teamId: 'haas' },
      { id: 'bearman', name: 'Oliver Bearman', number: '87', nationality: 'Reino Unido', teamId: 'haas' },
      { id: 'lawson', name: 'Liam Lawson', number: '30', nationality: 'Nova Zelândia', teamId: 'rb' },
      { id: 'lindblad', name: 'Arvid Lindblad', number: '41', nationality: 'Reino Unido', teamId: 'rb' },
      { id: 'sainz', name: 'Carlos Sainz', number: '55', nationality: 'Espanha', teamId: 'williams' },
      { id: 'albon', name: 'Alexander Albon', number: '23', nationality: 'Tailândia', teamId: 'williams' },
      { id: 'hulkenberg', name: 'Nico Hülkenberg', number: '27', nationality: 'Alemanha', teamId: 'audi' },
      { id: 'bortoleto', name: 'Gabriel Bortoleto', number: '5', nationality: 'Brasil', teamId: 'audi' },
      { id: 'perez', name: 'Sergio Pérez', number: '11', nationality: 'México', teamId: 'cadillac' },
      { id: 'bottas', name: 'Valtteri Bottas', number: '77', nationality: 'Finlândia', teamId: 'cadillac' },
    ],
    calendar: [
      { id: 'australia', name: 'GP da Austrália', location: 'Melbourne', date: '2026-03-08', circuit: 'Albert Park', status: 'completed', winner: 'Lando Norris' },
      { id: 'china', name: 'GP da China', location: 'Xangai', date: '2026-03-15', circuit: 'Shanghai International Circuit', status: 'completed', winner: 'Oscar Piastri' },
      { id: 'japan', name: 'GP do Japão', location: 'Suzuka', date: '2026-03-29', circuit: 'Suzuka International Racing Course', status: 'completed', winner: 'Max Verstappen' },
      { id: 'bahrain', name: 'GP do Bahrein', location: 'Sakhir', date: '2026-04-12', circuit: 'Bahrain International Circuit', status: 'cancelled' },
      { id: 'saudi', name: 'GP da Arábia Saudita', location: 'Jeddah', date: '2026-04-19', circuit: 'Jeddah Corniche Circuit', status: 'cancelled' },
      { id: 'miami', name: 'GP de Miami', location: 'Miami', date: '2026-05-03', circuit: 'Miami International Autodrome', status: 'upcoming' },
      { id: 'canada', name: 'GP do Canadá', location: 'Montreal', date: '2026-05-24', circuit: 'Circuit Gilles Villeneuve', status: 'upcoming' },
      { id: 'monaco', name: 'GP de Mônaco', location: 'Monte Carlo', date: '2026-06-07', circuit: 'Circuit de Monaco', status: 'upcoming' },
      { id: 'spain', name: 'GP da Espanha', location: 'Barcelona', date: '2026-06-14', circuit: 'Circuit de Barcelona-Catalunya', status: 'upcoming' },
      { id: 'austria', name: 'GP da Áustria', location: 'Spielberg', date: '2026-06-28', circuit: 'Red Bull Ring', status: 'upcoming' },
      { id: 'britain', name: 'GP da Grã-Bretanha', location: 'Silverstone', date: '2026-07-05', circuit: 'Silverstone Circuit', status: 'upcoming' },
      { id: 'belgium', name: 'GP da Bélgica', location: 'Spa', date: '2026-07-19', circuit: 'Circuit de Spa-Francorchamps', status: 'upcoming' },
      { id: 'hungary', name: 'GP da Hungria', location: 'Budapeste', date: '2026-07-26', circuit: 'Hungaroring', status: 'upcoming' },
      { id: 'netherlands', name: 'GP dos Países Baixos', location: 'Zandvoort', date: '2026-08-23', circuit: 'Circuit Zandvoort', status: 'upcoming' },
      { id: 'italy', name: 'GP da Itália', location: 'Monza', date: '2026-09-06', circuit: 'Autodromo Nazionale Monza', status: 'upcoming' },
      { id: 'madrid', name: 'GP de Madri', location: 'Madri', date: '2026-09-13', circuit: 'Madrid Street Circuit', status: 'upcoming' },
      { id: 'azerbaijan', name: 'GP do Azerbaijão', location: 'Baku', date: '2026-09-26', circuit: 'Baku City Circuit', status: 'upcoming' },
      { id: 'singapore', name: 'GP de Singapura', location: 'Marina Bay', date: '2026-10-11', circuit: 'Marina Bay Street Circuit', status: 'upcoming' },
      { id: 'usa', name: 'GP dos EUA', location: 'Austin', date: '2026-10-25', circuit: 'Circuit of the Americas', status: 'upcoming' },
      { id: 'mexico', name: 'GP do México', location: 'Cidade do México', date: '2026-11-01', circuit: 'Autódromo Hermanos Rodríguez', status: 'upcoming' },
      { id: 'brazil', name: 'GP de São Paulo', location: 'São Paulo', date: '2026-11-08', circuit: 'Autódromo de Interlagos', status: 'upcoming' },
      { id: 'vegas', name: 'GP de Las Vegas', location: 'Las Vegas', date: '2026-11-21', circuit: 'Las Vegas Strip Circuit', status: 'upcoming' },
      { id: 'qatar', name: 'GP do Catar', location: 'Lusail', date: '2026-11-29', circuit: 'Lusail International Circuit', status: 'upcoming' },
      { id: 'abudhabi', name: 'GP de Abu Dhabi', location: 'Yas Marina', date: '2026-12-06', circuit: 'Yas Marina Circuit', status: 'upcoming' },
    ],
    standings: {
      drivers: [
        { position: 1, name: 'Kimi Antonelli', points: 72, team: 'Mercedes' },
        { position: 2, name: 'George Russell', points: 63, team: 'Mercedes' },
        { position: 3, name: 'Charles Leclerc', points: 49, team: 'Ferrari' },
        { position: 4, name: 'Lewis Hamilton', points: 41, team: 'Ferrari' },
        { position: 5, name: 'Lando Norris', points: 25, team: 'McLaren' },
        { position: 6, name: 'Oscar Piastri', points: 21, team: 'McLaren' },
        { position: 7, name: 'Oliver Bearman', points: 17, team: 'Haas' },
        { position: 8, name: 'Pierre Gasly', points: 15, team: 'Alpine' },
        { position: 9, name: 'Max Verstappen', points: 12, team: 'Red Bull' },
        { position: 10, name: 'Liam Lawson', points: 10, team: 'RB' },
        { position: 11, name: 'Arvid Lindblad', points: 4, team: 'RB' },
        { position: 12, name: 'Isack Hadjar', points: 4, team: 'Red Bull' },
        { position: 13, name: 'Gabriel Bortoleto', points: 2, team: 'Audi' },
        { position: 14, name: 'Carlos Sainz', points: 2, team: 'Williams' },
        { position: 15, name: 'Esteban Ocon', points: 1, team: 'Haas' },
        { position: 16, name: 'Franco Colapinto', points: 1, team: 'Alpine' },
      ],
      constructors: [
        { position: 1, name: 'Mercedes', points: 135 },
        { position: 2, name: 'Ferrari', points: 90 },
        { position: 3, name: 'McLaren', points: 46 },
        { position: 4, name: 'Haas F1 Team', points: 18 },
        { position: 5, name: 'Alpine F1 Team', points: 16 },
        { position: 6, name: 'Red Bull Racing', points: 16 },
        { position: 7, name: 'Racing Bulls', points: 14 },
        { position: 8, name: 'Audi', points: 2 },
        { position: 9, name: 'Williams', points: 2 },
        { position: 10, name: 'Cadillac F1 Team', points: 0 },
        { position: 11, name: 'Aston Martin', points: 0 },
      ]
    }
  },
  {
    id: 'wec',
    name: 'WEC',
    fullName: 'World Endurance Championship',
    description: 'Corridas de longa duração que testam a resistência de máquinas e pilotos, incluindo as lendárias 24 Horas de Le Mans.',
    longDescription: 'O FIA WEC é o campeonato mundial de corridas de resistência. A categoria principal é a Hypercar (LMH e LMDh), onde grandes fabricantes como Ferrari, Toyota, Porsche e BMW competem com protótipos híbridos sofisticados. Além dos Hypercars, a categoria conta com a classe LMGT3 para carros baseados em modelos de produção. As corridas variam de 6 a 24 horas de duração, exigindo trocas de pilotos (geralmente 3 por carro), gerenciamento estratégico de pneus e combustível, e confiabilidade mecânica absoluta. O ponto alto da temporada são as 24 Horas de Le Mans, a corrida mais famosa do mundo.',
    icon: 'Timer',
    teams: [
      { id: 'toyota-racing', name: 'Toyota Racing', color: '#E4002B', class: 'Hypercar', car: 'Toyota GR010 Hybrid' },
      { id: 'cadillac-jota', name: 'Cadillac Hertz Team Jota', color: '#FFD700', class: 'Hypercar', car: 'Cadillac V-Series.R' },
      { id: 'bmw-wrt', name: 'BMW M Team WRT', color: '#0033A0', class: 'Hypercar', car: 'BMW M Hybrid V8' },
      { id: 'ferrari-af', name: 'Ferrari AF Corse', color: '#C80000', class: 'Hypercar', car: 'Ferrari 499P' },
      { id: 'genesis-magma', name: 'Genesis Magma Racing', color: '#FF4F00', class: 'Hypercar', car: 'Genesis LMDh' },
      { id: 'alpine-endurance', name: 'Alpine Endurance Team', color: '#005AFF', class: 'Hypercar', car: 'Alpine A424' },
      { id: 'aston-martin-thor', name: 'Aston Martin Thor Team', color: '#006F62', class: 'Hypercar', car: 'Aston Martin Valkyrie AMR-LMH' },
      { id: 'garage-59', name: 'Garage 59', color: '#000000', class: 'LMGT3', car: 'McLaren 720S GT3 Evo' },
      { id: 'vista-af', name: 'Vista AF Corse', color: '#FFFFFF', class: 'LMGT3', car: 'Ferrari 296 GT3' },
      { id: 'heart-of-racing', name: 'Heart of Racing Team', color: '#002B5C', class: 'LMGT3', car: 'Aston Martin Vantage AMR GT3 Evo' },
      { id: 'team-wrt-gt3', name: 'Team WRT', color: '#FF0000', class: 'LMGT3', car: 'BMW M4 GT3' },
    ],
    drivers: [
      { id: 'conway', name: 'Mike Conway', number: '7', nationality: 'Reino Unido', teamId: 'toyota-racing' },
      { id: 'kobayashi', name: 'Kamui Kobayashi', number: '7', nationality: 'Japão', teamId: 'toyota-racing' },
      { id: 'devries', name: 'Nyck de Vries', number: '7', nationality: 'Países Baixos', teamId: 'toyota-racing' },
      { id: 'buemi', name: 'Sébastien Buemi', number: '8', nationality: 'Suíça', teamId: 'toyota-racing' },
      { id: 'hartley', name: 'Brendon Hartley', number: '8', nationality: 'Nova Zelândia', teamId: 'toyota-racing' },
      { id: 'hirakawa', name: 'Ryō Hirakawa', number: '8', nationality: 'Japão', teamId: 'toyota-racing' },
      { id: 'lynn', name: 'Alexander Lynn', number: '12', nationality: 'Reino Unido', teamId: 'cadillac-jota' },
      { id: 'stevens', name: 'William Stevens', number: '12', nationality: 'Reino Unido', teamId: 'cadillac-jota' },
      { id: 'nato', name: 'Norman Nato', number: '12', nationality: 'França', teamId: 'cadillac-jota' },
      { id: 'bourdais', name: 'Sébastien Bourdais', number: '38', nationality: 'França', teamId: 'cadillac-jota' },
      { id: 'bamber', name: 'Earl Bamber', number: '38', nationality: 'Nova Zelândia', teamId: 'cadillac-jota' },
      { id: 'aitken', name: 'Jack Aitken', number: '38', nationality: 'Reino Unido', teamId: 'cadillac-jota' },
      { id: 'magnussen', name: 'Kevin Magnussen', number: '15', nationality: 'Dinamarca', teamId: 'bmw-wrt' },
      { id: 'marciello', name: 'Raffaele Marciello', number: '15', nationality: 'Suíça', teamId: 'bmw-wrt' },
      { id: 'vanthoor', name: 'Dries Vanthoor', number: '15', nationality: 'Bélgica', teamId: 'bmw-wrt' },
      { id: 'frijns', name: 'Robin Frijns', number: '20', nationality: 'Países Baixos', teamId: 'bmw-wrt' },
      { id: 'rast', name: 'René Rast', number: '20', nationality: 'Alemanha', teamId: 'bmw-wrt' },
      { id: 'vanderlinde', name: 'Sheldon van der Linde', number: '20', nationality: 'África do Sul', teamId: 'bmw-wrt' },
      { id: 'fuoco', name: 'Antonio Fuoco', number: '50', nationality: 'Itália', teamId: 'ferrari-af' },
      { id: 'nielsen', name: 'Nicklas Nielsen', number: '50', nationality: 'Dinamarca', teamId: 'ferrari-af' },
      { id: 'molina', name: 'Miguel Molina', number: '50', nationality: 'Espanha', teamId: 'ferrari-af' },
      { id: 'pierguidi', name: 'Alessandro Pier Guidi', number: '51', nationality: 'Itália', teamId: 'ferrari-af' },
      { id: 'calado', name: 'James Calado', number: '51', nationality: 'Reino Unido', teamId: 'ferrari-af' },
      { id: 'giovinazzi', name: 'Antonio Giovinazzi', number: '51', nationality: 'Itália', teamId: 'ferrari-af' },
      { id: 'lotterer', name: 'André Lotterer', number: '17', nationality: 'Alemanha', teamId: 'genesis-magma' },
      { id: 'derani-wec', name: 'Luis Felipe Derani', number: '17', nationality: 'Brasil', teamId: 'genesis-magma' },
      { id: 'jaubert', name: 'Mathys Jaubert', number: '17', nationality: 'França', teamId: 'genesis-magma' },
      { id: 'jaminet', name: 'Mathieu Jaminet', number: '19', nationality: 'França', teamId: 'genesis-magma' },
      { id: 'chatin', name: 'Paul-Loup Chatin', number: '19', nationality: 'França', teamId: 'genesis-magma' },
      { id: 'juncadella', name: 'Daniel Juncadella', number: '19', nationality: 'Espanha', teamId: 'genesis-magma' },
      { id: 'dacosta', name: 'António Félix da Costa', number: '35', nationality: 'Portugal', teamId: 'alpine-endurance' },
      { id: 'milesi', name: 'Charles Milesi', number: '35', nationality: 'França', teamId: 'alpine-endurance' },
      { id: 'habsburg', name: 'Ferdinand Habsburg', number: '35', nationality: 'Áustria', teamId: 'alpine-endurance' },
      { id: 'makowiecki', name: 'Frédéric Makowiecki', number: '36', nationality: 'França', teamId: 'alpine-endurance' },
      { id: 'gounon', name: 'Jules Gounon', number: '36', nationality: 'França', teamId: 'alpine-endurance' },
      { id: 'martins', name: 'Victor Martins', number: '36', nationality: 'França', teamId: 'alpine-endurance' },
      { id: 'tincknell', name: 'Harry Tincknell', number: '007', nationality: 'Reino Unido', teamId: 'aston-martin-thor' },
      { id: 'gamble', name: 'Tom Gamble', number: '007', nationality: 'Reino Unido', teamId: 'aston-martin-thor' },
      { id: 'gunn', name: 'Ross Gunn', number: '007', nationality: 'Reino Unido', teamId: 'aston-martin-thor' },
      { id: 'riberas', name: 'Alex Riberas', number: '009', nationality: 'Espanha', teamId: 'aston-martin-thor' },
      { id: 'sorensen', name: 'Marco Sørensen', number: '009', nationality: 'Dinamarca', teamId: 'aston-martin-thor' },
      { id: 'deangelis', name: 'Roman De Angelis', number: '009', nationality: 'Canadá', teamId: 'aston-martin-thor' },
      { id: 'au', name: 'Antares Au', number: '10', nationality: 'Hong Kong', teamId: 'garage-59' },
      { id: 'fleming', name: 'Tom Fleming', number: '10', nationality: 'Reino Unido', teamId: 'garage-59' },
      { id: 'kirchhofer', name: 'Marvin Kirchhöfer', number: '10', nationality: 'Alemanha', teamId: 'garage-59' },
      { id: 'gehrsitz', name: 'Finn Gehrsitz', number: '58', nationality: 'Alemanha', teamId: 'garage-59' },
      { id: 'goethe', name: 'Benjamin Goethe', number: '58', nationality: 'Mônaco', teamId: 'garage-59' },
      { id: 'west', name: 'Alexander West', number: '58', nationality: 'Suécia', teamId: 'garage-59' },
      { id: 'heriau', name: 'François Hériau', number: '21', nationality: 'França', teamId: 'vista-af' },
      { id: 'mann', name: 'Simon Mann', number: 'EUA', nationality: 'EUA', teamId: 'vista-af' },
      { id: 'rovera', name: 'Alessio Rovera', number: '21', nationality: 'Itália', teamId: 'vista-af' },
      { id: 'castellacci', name: 'Francesco Castellacci', number: '54', nationality: 'Itália', teamId: 'vista-af' },
      { id: 'flohr', name: 'Thomas Flohr', number: '54', nationality: 'Suíça', teamId: 'vista-af' },
      { id: 'rigon', name: 'Davide Rigon', number: '54', nationality: 'Itália', teamId: 'vista-af' },
      { id: 'adam', name: 'Jonny Adam', number: '23', nationality: 'Reino Unido', teamId: 'heart-of-racing' },
      { id: 'barrichello-edu', name: 'Eduardo Barrichello', number: '23', nationality: 'Brasil', teamId: 'heart-of-racing' },
      { id: 'newell', name: 'Gray Newell', number: '23', nationality: 'EUA', teamId: 'heart-of-racing' },
      { id: 'drudi', name: 'Mattia Drudi', number: '27', nationality: 'Itália', teamId: 'heart-of-racing' },
      { id: 'james', name: 'Ian James', number: '27', nationality: 'Reino Unido', teamId: 'heart-of-racing' },
      { id: 'robichon', name: 'Zacharie Robichon', number: '27', nationality: 'Canadá', teamId: 'heart-of-racing' },
      { id: 'farfus', name: 'Augusto Farfus', number: '32', nationality: 'Brasil', teamId: 'team-wrt-gt3' },
      { id: 'gelael', name: 'Sean Gelael', number: '32', nationality: 'Indonésia', teamId: 'team-wrt-gt3' },
      { id: 'leung', name: 'Darren Leung', number: '32', nationality: 'Reino Unido', teamId: 'team-wrt-gt3' },
      { id: 'harper', name: 'Dan Harper', number: '69', nationality: 'Reino Unido', teamId: 'team-wrt-gt3' },
      { id: 'mcintosh', name: 'Anthony McIntosh', number: '69', nationality: 'EUA', teamId: 'team-wrt-gt3' },
      { id: 'thompson', name: 'Parker Thompson', number: '69', nationality: 'Canadá', teamId: 'team-wrt-gt3' },
    ],
    calendar: [
      { id: 'imola', name: '6 Horas de Imola', location: 'Imola', date: '2026-04-19', circuit: 'Autodromo Enzo e Dino Ferrari', status: 'upcoming' },
      { id: 'spa', name: '6 Horas de Spa-Francorchamps', location: 'Spa', date: '2026-05-09', circuit: 'Circuit de Spa-Francorchamps', status: 'upcoming' },
      { id: 'lemans', name: '24 Horas de Le Mans', location: 'Le Mans', date: '2026-06-14', circuit: 'Circuit de la Sarthe', status: 'upcoming' },
      { id: 'saopaulo', name: '6 Horas de São Paulo', location: 'São Paulo', date: '2026-07-12', circuit: 'Autódromo de Interlagos', status: 'upcoming' },
      { id: 'cota', name: 'Lone Star Le Mans', location: 'Austin', date: '2026-09-06', circuit: 'Circuit of the Americas', status: 'upcoming' },
      { id: 'fuji', name: '6 Horas de Fuji', location: 'Fuji', date: '2026-09-27', circuit: 'Fuji Speedway', status: 'upcoming' },
      { id: 'qatar', name: '1812km do Catar', location: 'Lusail', date: '2026-10-23', circuit: 'Lusail International Circuit', status: 'upcoming' },
      { id: 'bahrain', name: '8 Horas do Bahrein', location: 'Sakhir', date: '2026-11-07', circuit: 'Bahrain International Circuit', status: 'upcoming' },
    ]
  },
  {
    id: 'imsa',
    name: 'IMSA',
    fullName: 'IMSA SportsCar Championship',
    description: 'A principal categoria de endurance da América do Norte, com protótipos e carros de GT.',
    longDescription: 'O IMSA WeatherTech SportsCar Championship é a principal série de corridas de carros esportivos na América do Norte. A categoria de topo é a GTP (Grand Touring Prototype), que compartilha regulamentos técnicos com os Hypercars do WEC, permitindo que os carros compitam em ambos os campeonatos. Outras classes incluem LMP2 (protótipos), GTD Pro e GTD (carros GT3). O calendário inclui clássicos como as 24 Horas de Daytona e as 12 Horas de Sebring. Diferente do WEC, o IMSA é conhecido por corridas extremamente disputadas, com frequentes períodos de bandeira amarela que reagrupam o pelotão, garantindo finais emocionantes.',
    icon: 'Flag',
    teams: [
      { id: 'porsche-penske', name: 'Porsche Penske Motorsport', color: '#000000', class: 'GTP', car: 'Porsche 963' },
      { id: 'cadillac-wtr', name: 'Cadillac Wayne Taylor Racing', color: '#000000', class: 'GTP', car: 'Cadillac V-Series.R' },
      { id: 'aston-martin-thor-imsa', name: 'Aston Martin THOR Team', color: '#006F62', class: 'GTP', car: 'Aston Martin Valkyrie AMR-LMH' },
      { id: 'bmw-wrt-imsa', name: 'BMW M Team WRT', color: '#0033A0', class: 'GTP', car: 'BMW M Hybrid V8' },
      { id: 'cadillac-whelen', name: 'Cadillac Whelen', color: '#E4002B', class: 'GTP', car: 'Cadillac V-Series.R' },
      { id: 'acura-msr', name: 'Acura Meyer Shank Racing with Curb-Agajanian', color: '#FF0000', class: 'GTP', car: 'Acura ARX-06' },
      { id: 'jdc-miller', name: 'JDC–Miller MotorSports', color: '#FFFF00', class: 'GTP', car: 'Porsche 963' },
      { id: 'crowdstrike-apr', name: 'CrowdStrike Racing by APR', color: '#FF0000', class: 'LMP2', car: 'Oreca 07 Gibson' },
      { id: 'united-autosports', name: 'United Autosports USA', color: '#000080', class: 'LMP2', car: 'Oreca 07 Gibson' },
      { id: 'tower-motorsports', name: 'Tower Motorsports', color: '#FFA500', class: 'LMP2', car: 'Oreca 07 Gibson' },
      { id: 'tds-racing', name: 'TDS Racing', color: '#0000FF', class: 'LMP2', car: 'Oreca 07 Gibson' },
      { id: 'era-motorsport', name: 'Era Motorsport', color: '#000000', class: 'LMP2', car: 'Oreca 07 Gibson' },
      { id: 'intersport-racing', name: 'Intersport Racing', color: '#FFFFFF', class: 'LMP2', car: 'Oreca 07 Gibson' },
      { id: 'inter-europol', name: 'Inter Europol Competition', color: '#FFFF00', class: 'LMP2', car: 'Oreca 07 Gibson' },
    ],
    drivers: [
      { id: 'campbell', name: 'Matt Campbell', number: '6', nationality: 'Austrália', teamId: 'porsche-penske' },
      { id: 'estre', name: 'Kévin Estre', number: '6', nationality: 'França', teamId: 'porsche-penske' },
      { id: 'vanthoor-l', name: 'Laurens Vanthoor', number: '6', nationality: 'Bélgica', teamId: 'porsche-penske' },
      { id: 'andlauer', name: 'Julien Andlauer', number: '7', nationality: 'França', teamId: 'porsche-penske' },
      { id: 'heinrich', name: 'Laurin Heinrich', number: '7', nationality: 'Alemanha', teamId: 'porsche-penske' },
      { id: 'nasr', name: 'Felipe Nasr', number: '7', nationality: 'Brasil', teamId: 'porsche-penske' },
      { id: 'albuquerque', name: 'Filipe Albuquerque', number: '10', nationality: 'Portugal', teamId: 'cadillac-wtr' },
      { id: 'stevens-imsa', name: 'Will Stevens', number: '10', nationality: 'Reino Unido', teamId: 'cadillac-wtr' },
      { id: 'taylor-r', name: 'Ricky Taylor', number: '10', nationality: 'EUA', teamId: 'cadillac-wtr' },
      { id: 'deletraz', name: 'Louis Delétraz', number: '40', nationality: 'Suíça', teamId: 'cadillac-wtr' },
      { id: 'herta', name: 'Colton Herta', number: '40', nationality: 'EUA', teamId: 'cadillac-wtr' },
      { id: 'taylor-j', name: 'Jordan Taylor', number: '40', nationality: 'EUA', teamId: 'cadillac-wtr' },
      { id: 'deangelis-imsa', name: 'Roman De Angelis', number: '23', nationality: 'Canadá', teamId: 'aston-martin-thor-imsa' },
      { id: 'gunn-imsa', name: 'Ross Gunn', number: '23', nationality: 'Reino Unido', teamId: 'aston-martin-thor-imsa' },
      { id: 'riberas-imsa', name: 'Alex Riberas', number: '23', nationality: 'Espanha', teamId: 'aston-martin-thor-imsa' },
      { id: 'sorensen-imsa', name: 'Marco Sørensen', number: '23', nationality: 'Dinamarca', teamId: 'aston-martin-thor-imsa' },
      { id: 'frijns-imsa', name: 'Robin Frijns', number: '24', nationality: 'Países Baixos', teamId: 'bmw-wrt-imsa' },
      { id: 'vanderlinde-imsa', name: 'Sheldon van der Linde', number: '24', nationality: 'África do Sul', teamId: 'bmw-wrt-imsa' },
      { id: 'vanthoor-d-imsa', name: 'Dries Vanthoor', number: '24', nationality: 'Bélgica', teamId: 'bmw-wrt-imsa' },
      { id: 'rast-imsa', name: 'René Rast', number: '24', nationality: 'Alemanha', teamId: 'bmw-wrt-imsa' },
      { id: 'eng', name: 'Philipp Eng', number: '25', nationality: 'Áustria', teamId: 'bmw-wrt-imsa' },
      { id: 'magnussen-imsa', name: 'Kevin Magnussen', number: '25', nationality: 'Dinamarca', teamId: 'bmw-wrt-imsa' },
      { id: 'marciello-imsa', name: 'Raffaele Marciello', number: '25', nationality: 'Suíça', teamId: 'bmw-wrt-imsa' },
      { id: 'wittmann', name: 'Marco Wittmann', number: '25', nationality: 'Alemanha', teamId: 'bmw-wrt-imsa' },
      { id: 'aitken-imsa', name: 'Jack Aitken', number: '31', nationality: 'Reino Unido', teamId: 'cadillac-whelen' },
      { id: 'bamber-imsa', name: 'Earl Bamber', number: '31', nationality: 'Nova Zelândia', teamId: 'cadillac-whelen' },
      { id: 'vesti', name: 'Frederik Vesti', number: '31', nationality: 'Dinamarca', teamId: 'cadillac-whelen' },
      { id: 'zilisch', name: 'Connor Zilisch', number: '31', nationality: 'EUA', teamId: 'cadillac-whelen' },
      { id: 'allmendinger', name: 'A. J. Allmendinger', number: '60', nationality: 'EUA', teamId: 'acura-msr' },
      { id: 'blomqvist', name: 'Tom Blomqvist', number: '60', nationality: 'Reino Unido', teamId: 'acura-msr' },
      { id: 'braun', name: 'Colin Braun', number: '60', nationality: 'EUA', teamId: 'acura-msr' },
      { id: 'dixon', name: 'Scott Dixon', number: '60', nationality: 'Nova Zelândia', teamId: 'acura-msr' },
      { id: 'ohta', name: 'Kakunoshin Ohta', number: '93', nationality: 'Japão', teamId: 'acura-msr' },
      { id: 'palou', name: 'Álex Palou', number: '93', nationality: 'Espanha', teamId: 'acura-msr' },
      { id: 'yelloly', name: 'Nick Yelloly', number: '93', nationality: 'Reino Unido', teamId: 'acura-msr' },
      { id: 'vanderzande', name: 'Renger van der Zande', number: '93', nationality: 'Países Baixos', teamId: 'acura-msr' },
      { id: 'frederick', name: 'Kaylen Frederick', number: '5', nationality: 'EUA', teamId: 'jdc-miller' },
      { id: 'vanderhelm', name: 'Tijmen van der Helm', number: '5', nationality: 'Países Baixos', teamId: 'jdc-miller' },
      { id: 'pino', name: 'Nico Pino', number: '5', nationality: 'Chile', teamId: 'jdc-miller' },
      { id: 'kurtz', name: 'George Kurtz', number: '04', nationality: 'EUA', teamId: 'crowdstrike-apr' },
      { id: 'quinn', name: 'Alex Quinn', number: '04', nationality: 'Reino Unido', teamId: 'crowdstrike-apr' },
      { id: 'sowery', name: 'Toby Sowery', number: '04', nationality: 'Reino Unido', teamId: 'crowdstrike-apr' },
      { id: 'jakobsen', name: 'Malthe Jakobsen', number: '04', nationality: 'Dinamarca', teamId: 'crowdstrike-apr' },
      { id: 'fayer', name: 'Phil Fayer', number: '2', nationality: 'Canadá', teamId: 'united-autosports' },
      { id: 'hanley', name: 'Ben Hanley', number: '2', nationality: 'Reino Unido', teamId: 'united-autosports' },
      { id: 'jensen', name: 'Mikkel Jensen', number: '2', nationality: 'Dinamarca', teamId: 'united-autosports' },
      { id: 'mcelrea', name: 'Hunter McElrea', number: '2', nationality: 'Nova Zelândia', teamId: 'united-autosports' },
      { id: 'diresta', name: 'Paul di Resta', number: '22', nationality: 'Reino Unido', teamId: 'united-autosports' },
      { id: 'goldburg', name: 'Dan Goldburg', number: '22', nationality: 'EUA', teamId: 'united-autosports' },
      { id: 'lindh', name: 'Rasmus Lindh', number: '22', nationality: 'Suécia', teamId: 'united-autosports' },
      { id: 'alvarez', name: 'Sebastián Álvarez', number: '8', nationality: 'México', teamId: 'tower-motorsports' },
      { id: 'bourdais-imsa', name: 'Sébastien Bourdais', number: '8', nationality: 'França', teamId: 'tower-motorsports' },
      { id: 'farano', name: 'John Farano', number: '8', nationality: 'Canadá', teamId: 'tower-motorsports' },
      { id: 'simpson', name: 'Kyffin Simpson', number: '8', nationality: 'Ilhas Cayman', teamId: 'tower-motorsports' },
      { id: 'hansson', name: 'David Heinemeier Hansson', number: '11', nationality: 'Dinamarca', teamId: 'tds-racing' },
      { id: 'lutke', name: 'Tobias Lütke', number: '11', nationality: 'Canadá', teamId: 'tds-racing' },
      { id: 'milesi-imsa', name: 'Charles Milesi', number: '11', nationality: 'França', teamId: 'tds-racing' },
      { id: 'beche', name: 'Mathias Beche', number: '11', nationality: 'Suíça', teamId: 'tds-racing' },
      { id: 'abel', name: 'Jacob Abel', number: '18', nationality: 'EUA', teamId: 'era-motorsport' },
      { id: 'habsburg-imsa', name: 'Ferdinand Habsburg', number: '18', nationality: 'Áustria', teamId: 'era-motorsport' },
      { id: 'rao', name: 'Naveen Rao', number: '18', nationality: 'EUA', teamId: 'era-motorsport' },
      { id: 'sargeant', name: 'Logan Sargeant', number: '18', nationality: 'EUA', teamId: 'era-motorsport' },
      { id: 'field', name: 'Jon Field', number: '37', nationality: 'EUA', teamId: 'intersport-racing' },
      { id: 'jarvis', name: 'Oliver Jarvis', number: '37', nationality: 'Reino Unido', teamId: 'intersport-racing' },
      { id: 'lucas', name: 'Seth Lucas', number: '37', nationality: 'EUA', teamId: 'intersport-racing' },
      { id: 'clarke', name: 'Jeremy Clarke', number: '43', nationality: 'EUA', teamId: 'inter-europol' },
      { id: 'dillmann', name: 'Tom Dillmann', number: '43', nationality: 'França', teamId: 'inter-europol' },
      { id: 'garg', name: 'Bijoy Garg', number: '43', nationality: 'EUA', teamId: 'inter-europol' },
    ],
    calendar: [
      { id: 'roar', name: 'Roar Before The Rolex 24', location: 'Daytona', date: '2026-01-18', circuit: 'Daytona International Speedway', status: 'completed', winner: 'Cadillac #31' },
      { id: 'daytona', name: 'Rolex 24 At Daytona', location: 'Daytona', date: '2026-01-25', circuit: 'Daytona International Speedway', status: 'completed', winner: 'Porsche #6' },
      { id: 'sebring', name: '12 Horas de Sebring', location: 'Sebring', date: '2026-03-21', circuit: 'Sebring International Raceway', status: 'completed', winner: 'Acura #60' },
      { id: 'longbeach', name: 'Grand Prix of Long Beach', location: 'Long Beach', date: '2026-04-19', circuit: 'Long Beach Street Circuit', status: 'upcoming' },
      { id: 'lagunaseca', name: 'Laguna Seca', location: 'Monterey', date: '2026-05-03', circuit: 'WeatherTech Raceway Laguna Seca', status: 'upcoming' },
      { id: 'detroit', name: 'Detroit Grand Prix', location: 'Detroit', date: '2026-05-30', circuit: 'Detroit Street Circuit', status: 'upcoming' },
      { id: 'watkins', name: 'Six Hours of The Glen', location: 'Watkins Glen', date: '2026-06-28', circuit: 'Watkins Glen International', status: 'upcoming' },
      { id: 'mosport', name: 'Canadian Tire Motorsport Park', location: 'Bowmanville', date: '2026-07-12', circuit: 'Canadian Tire Motorsport Park', status: 'upcoming' },
      { id: 'roadamerica', name: '6 Horas de Road America', location: 'Elkhart Lake', date: '2026-08-02', circuit: 'Road America', status: 'upcoming' },
      { id: 'vir', name: 'GT Challenge at VIR', location: 'Alton', date: '2026-08-23', circuit: 'Virginia International Raceway', status: 'upcoming' },
      { id: 'indianapolis', name: 'Battle On The Bricks', location: 'Indianapolis', date: '2026-09-20', circuit: 'Indianapolis Motor Speedway', status: 'upcoming' },
      { id: 'roadatlanta', name: 'Petit Le Mans', location: 'Braselton', date: '2026-10-03', circuit: 'Michelin Raceway Road Atlanta', status: 'upcoming' },
    ],
    standings: {
      teams: [
        { position: 1, name: 'Porsche Penske Motorsport', points: 755, extra: '#7' },
        { position: 2, name: 'Cadillac Whelen', points: 675, extra: '#31' },
        { position: 3, name: 'Porsche Penske Motorsport', points: 654, extra: '#6' },
        { position: 4, name: 'BMW M Team WRT', points: 606, extra: '#24' },
        { position: 5, name: 'Acura Meyer Shank Racing', points: 567, extra: '#93' },
        { position: 6, name: 'Acura Meyer Shank Racing', points: 560, extra: '#60' },
        { position: 7, name: 'Cadillac Wayne Taylor Racing', points: 548, extra: '#40' },
        { position: 8, name: 'JDC-Miller Motorsports', points: 519, extra: '#5' },
        { position: 9, name: 'BMW M Team WRT', points: 482, extra: '#25' },
        { position: 10, name: 'Aston Martin Thor Team', points: 472, extra: '#23' },
        { position: 11, name: 'Cadillac Wayne Taylor Racing', points: 455, extra: '#10' },
      ]
    }
  },
  {
    id: 'rally',
    name: 'Rally',
    fullName: 'WRC - World Rally Championship',
    description: 'Pilotos enfrentando terrenos extremos, de neve a cascalho, em velocidades incríveis.',
    longDescription: 'O WRC é a competição de rali de mais alto nível da FIA. Pilotos e navegadores competem em carros "Rally1" híbridos em superfícies que variam de asfalto liso a cascalho bruto, neve e gelo. Cada rali é dividido em "estágios" cronometrados em estradas fechadas ao público. O objetivo é completar os estágios no menor tempo possível. Entre os estágios, os carros circulam em estradas públicas, devendo obedecer às leis de trânsito. O WRC exige uma habilidade de condução incomparável e uma confiança cega entre o piloto e o navegador, que lê as "notas de ritmo" para descrever o que vem pela frente em alta velocidade.',
    icon: 'Mountain',
    teams: [
      { id: 'hyundai-wrc', name: 'Hyundai Shell Mobis WRT', color: '#003478', car: 'Hyundai i20 N Rally1' },
      { id: 'toyota-wrc', name: 'Toyota Gazoo Racing WRT', color: '#E4002B', car: 'Toyota GR Yaris Rally1' },
      { id: 'msport-ford', name: 'M-Sport Ford WRT', color: '#0000FF', car: 'Ford Puma Rally1' },
    ],
    drivers: [
      { id: 'neuville', name: 'Thierry Neuville', number: '11', nationality: 'Bélgica', teamId: 'hyundai-wrc' },
      { id: 'fourmaux', name: 'Adrien Fourmaux', number: '16', nationality: 'França', teamId: 'hyundai-wrc' },
      { id: 'lappi', name: 'Esapekka Lappi', number: '4', nationality: 'Finlândia', teamId: 'hyundai-wrc' },
      { id: 'sordo', name: 'Dani Sordo', number: '6', nationality: 'Espanha', teamId: 'hyundai-wrc' },
      { id: 'paddon', name: 'Hayden Paddon', number: '20', nationality: 'Nova Zelândia', teamId: 'hyundai-wrc' },
      { id: 'ogier', name: 'Sébastien Ogier', number: '1', nationality: 'França', teamId: 'toyota-wrc' },
      { id: 'pajari', name: 'Sami Pajari', number: '5', nationality: 'Finlândia', teamId: 'toyota-wrc' },
      { id: 'katsuta', name: 'Takamoto Katsuta', number: '18', nationality: 'Japão', teamId: 'toyota-wrc' },
      { id: 'evans', name: 'Elfyn Evans', number: '33', nationality: 'Reino Unido', teamId: 'toyota-wrc' },
      { id: 'solberg', name: 'Oliver Solberg', number: '99', nationality: 'Suécia', teamId: 'toyota-wrc' },
      { id: 'munster', name: 'Grégoire Munster', number: '13', nationality: 'Luxemburgo', teamId: 'msport-ford' },
      { id: 'mcerlean', name: 'Josh McErlean', number: '55', nationality: 'Irlanda', teamId: 'msport-ford' },
      { id: 'armstrong', name: 'Jon Armstrong', number: '95', nationality: 'Irlanda', teamId: 'msport-ford' },
      { id: 'sesks', name: 'Mārtiņš Sesks', number: '22', nationality: 'Letônia', teamId: 'msport-ford' },
    ],
    calendar: [
      { id: 'montecarlo', name: 'Rallye Monte-Carlo', location: 'Mônaco', date: '2026-01-25', circuit: 'Asfalto/Gelo', status: 'completed', winner: 'Thierry Neuville' },
      { id: 'sweden', name: 'Rally Sweden', location: 'Umeå', date: '2026-02-15', circuit: 'Neve', status: 'completed', winner: 'Esapekka Lappi' },
      { id: 'safari', name: 'Safari Rally Kenya', location: 'Naivasha', date: '2026-03-15', circuit: 'Cascalho', status: 'completed', winner: 'Kalle Rovanperä' },
      { id: 'croatia', name: 'Croatia Rally', location: 'Zagreb', date: '2026-04-12', circuit: 'Asfalto', status: 'upcoming' },
      { id: 'canarias', name: 'Rally Islas Canarias', location: 'Ilhas Canárias', date: '2026-04-26', circuit: 'Asfalto', status: 'upcoming' },
      { id: 'portugal', name: 'Rally de Portugal', location: 'Matosinhos', date: '2026-05-10', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'japan', name: 'Rally Japan', location: 'Toyota', date: '2026-05-31', circuit: 'Asfalto', status: 'upcoming' },
      { id: 'greece', name: 'Acropolis Rally Greece', location: 'Lamia', date: '2026-06-28', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'estonia', name: 'Rally Estonia', location: 'Tartu', date: '2026-07-19', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'finland', name: 'Rally Finland', location: 'Jyväskylä', date: '2026-08-02', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'paraguay', name: 'Rally del Paraguay', location: 'Encarnación', date: '2026-08-30', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'chile', name: 'Rally Chile Bio Bío', location: 'Concepción', date: '2026-09-13', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'sardegna', name: 'Rally Italia Sardegna', location: 'Olbia', date: '2026-10-04', circuit: 'Cascalho', status: 'upcoming' },
      { id: 'saudi', name: 'Rally Saudi Arabia', location: 'Jeddah', date: '2026-11-14', circuit: 'Cascalho', status: 'upcoming' },
    ],
    standings: {
      drivers: [
        { position: 1, name: 'Elfyn Evans', points: 66 },
        { position: 2, name: 'Oliver Solberg', points: 58 },
        { position: 3, name: 'Takamoto Katsuta', points: 55 },
        { position: 4, name: 'Adrien Fourmaux', points: 47 },
        { position: 5, name: 'Sami Pajari', points: 32 },
        { position: 6, name: 'Sébastien Ogier', points: 26 },
        { position: 7, name: 'Thierry Neuville', points: 25 },
        { position: 8, name: 'Esapekka Lappi', points: 21 },
        { position: 9, name: 'Robert Virves', points: 10 },
        { position: 10, name: 'Léo Rossel', points: 8 },
      ],
      constructors: [
        { position: 1, name: 'Toyota Gazoo Racing WRT', points: 157 },
        { position: 2, name: 'Hyundai Shell Mobis WRT', points: 114 },
        { position: 3, name: 'Toyota Gazoo Racing WRT2', points: 35 },
      ]
    }
  },
  {
    id: 'indy',
    name: 'IndyCar',
    fullName: 'NTT IndyCar Series',
    description: 'A categoria de monopostos mais veloz dos EUA, famosa pelas 500 Milhas de Indianápolis.',
    longDescription: 'A NTT IndyCar Series é a principal categoria de monopostos da América do Norte. Conhecida por sua incrível diversidade de circuitos, a categoria compete em ovais de alta velocidade, circuitos mistos permanentes e desafiadores circuitos de rua. O chassi Dallara IR-18 é padrão para todas as equipes, com motores V6 Twin-Turbo fornecidos pela Chevrolet e Honda. O ponto alto do automobilismo mundial são as 500 Milhas de Indianápolis (Indy 500), uma das provas da Tríplice Coroa do Automobilismo. A categoria é famosa pelo equilíbrio, onde a habilidade do piloto e a estratégia da equipe fazem a diferença real.',
    icon: 'Zap',
    teams: [
      { id: 'foyt', name: 'A. J. Foyt Enterprises', color: '#DC0000', car: 'Dallara IR-18 (Chevrolet)' },
      { id: 'andretti', name: 'Andretti Global', color: '#000000', car: 'Dallara IR-18 (Honda)' },
      { id: 'mclaren-indy', name: 'Arrow McLaren', color: '#FF8700', car: 'Dallara IR-18 (Chevrolet)' },
      { id: 'ganassi', name: 'Chip Ganassi Racing', color: '#0000FF', car: 'Dallara IR-18 (Honda)' },
      { id: 'dalecoyne', name: 'Dale Coyne Racing', color: '#000000', car: 'Dallara IR-18 (Honda)' },
      { id: 'dreyer', name: 'Dreyer & Reinbold Racing', color: '#000000', car: 'Dallara IR-18 (Chevrolet)' },
      { id: 'carpenter', name: 'Ed Carpenter Racing', color: '#000000', car: 'Dallara IR-18 (Chevrolet)' },
      { id: 'juncos', name: 'Juncos Hollinger Racing', color: '#000000', car: 'Dallara IR-18 (Chevrolet)' },
      { id: 'msr-indy', name: 'Meyer Shank Racing', color: '#FF00FF', car: 'Dallara IR-18 (Honda)' },
      { id: 'rahal', name: 'Rahal Letterman Lanigan Racing', color: '#000000', car: 'Dallara IR-18 (Honda)' },
      { id: 'penske-indy', name: 'Team Penske', color: '#DC0000', car: 'Dallara IR-18 (Chevrolet)' },
    ],
    drivers: [
      { id: 'collet', name: 'Caio Collet', number: '4', nationality: 'Brasil', teamId: 'foyt' },
      { id: 'ferrucci', name: 'Santino Ferrucci', number: '14', nationality: 'EUA', teamId: 'foyt' },
      { id: 'power', name: 'Will Power', number: '26', nationality: 'Austrália', teamId: 'andretti' },
      { id: 'kirkwood', name: 'Kyle Kirkwood', number: '27', nationality: 'EUA', teamId: 'andretti' },
      { id: 'ericsson', name: 'Marcus Ericsson', number: '28', nationality: 'Suécia', teamId: 'andretti' },
      { id: 'oward', name: 'Pato O\'Ward', number: '5', nationality: 'México', teamId: 'mclaren-indy' },
      { id: 'siegel', name: 'Nolan Siegel', number: '6', nationality: 'EUA', teamId: 'mclaren-indy' },
      { id: 'lundgaard', name: 'Christian Lundgaard', number: '7', nationality: 'Dinamarca', teamId: 'mclaren-indy' },
      { id: 'hunterreay', name: 'Ryan Hunter-Reay', number: '31', nationality: 'EUA', teamId: 'mclaren-indy' },
      { id: 'simpson-indy', name: 'Kyffin Simpson', number: '8', nationality: 'Ilhas Cayman', teamId: 'ganassi' },
      { id: 'dixon-indy', name: 'Scott Dixon', number: '9', nationality: 'Nova Zelândia', teamId: 'ganassi' },
      { id: 'palou-indy', name: 'Álex Palou', number: '10', nationality: 'Espanha', teamId: 'ganassi' },
      { id: 'grosjean', name: 'Romain Grosjean', number: '18', nationality: 'França', teamId: 'dalecoyne' },
      { id: 'hauger', name: 'Dennis Hauger', number: '19', nationality: 'Noruega', teamId: 'dalecoyne' },
      { id: 'daly', name: 'Conor Daly', number: '23', nationality: 'EUA', teamId: 'dreyer' },
      { id: 'harvey', name: 'Jack Harvey', number: '24', nationality: 'Reino Unido', teamId: 'dreyer' },
      { id: 'rossi', name: 'Alexander Rossi', number: '20', nationality: 'EUA', teamId: 'carpenter' },
      { id: 'rasmussen', name: 'Christian Rasmussen', number: '21', nationality: 'Dinamarca', teamId: 'carpenter' },
      { id: 'carpenter-driver', name: 'Ed Carpenter', number: '33', nationality: 'EUA', teamId: 'carpenter' },
      { id: 'veekay', name: 'Rinus VeeKay', number: '76', nationality: 'Países Baixos', teamId: 'juncos' },
      { id: 'robb', name: 'Sting Ray Robb', number: '77', nationality: 'EUA', teamId: 'juncos' },
      { id: 'castroneves-indy', name: 'Hélio Castroneves', number: '06', nationality: 'Brasil', teamId: 'msr-indy' },
      { id: 'rosenqvist', name: 'Felix Rosenqvist', number: '60', nationality: 'Suécia', teamId: 'msr-indy' },
      { id: 'armstrong-indy', name: 'Marcus Armstrong', number: '66', nationality: 'Nova Zelândia', teamId: 'msr-indy' },
      { id: 'rahal-driver', name: 'Graham Rahal', number: '15', nationality: 'EUA', teamId: 'rahal' },
      { id: 'foster', name: 'Louis Foster', number: '45', nationality: 'Reino Unido', teamId: 'rahal' },
      { id: 'schumacher', name: 'Mick Schumacher', number: '47', nationality: 'Alemanha', teamId: 'rahal' },
      { id: 'sato', name: 'Takuma Sato', number: '75', nationality: 'Japão', teamId: 'rahal' },
      { id: 'newgarden', name: 'Josef Newgarden', number: '2', nationality: 'EUA', teamId: 'penske-indy' },
      { id: 'mclaughlin', name: 'Scott McLaughlin', number: '3', nationality: 'Nova Zelândia', teamId: 'penske-indy' },
      { id: 'malukas', name: 'David Malukas', number: '12', nationality: 'EUA', teamId: 'penske-indy' },
    ],
    calendar: [
      { id: 'st-pete', name: 'GP de St. Petersburg', location: 'St. Petersburg', date: '2026-03-01', circuit: 'Circuito de Rua', status: 'completed' },
      { id: 'phoenix', name: 'GP de Phoenix', location: 'Phoenix', date: '2026-03-07', circuit: 'Oval', status: 'completed' },
      { id: 'arlington', name: 'GP de Arlington', location: 'Arlington', date: '2026-03-15', circuit: 'Circuito de Rua', status: 'completed' },
      { id: 'barber', name: 'GP de Barber', location: 'Barber', date: '2026-03-25', circuit: 'Misto', status: 'completed' },
      { id: 'long-beach-indy', name: 'GP de Long Beach', location: 'Long Beach', date: '2026-04-19', circuit: 'Circuito de Rua', status: 'upcoming' },
      { id: 'indy-road', name: 'GP de Indianápolis (Misto)', location: 'Indianápolis', date: '2026-05-09', circuit: 'Misto', status: 'upcoming' },
      { id: 'indy-500', name: '110ª 500 Milhas de Indianápolis', location: 'Indianápolis', date: '2026-05-24', circuit: 'Oval', status: 'upcoming' },
      { id: 'detroit-indy', name: 'GP de Detroit', location: 'Detroit', date: '2026-05-31', circuit: 'Circuito de Rua', status: 'upcoming' },
      { id: 'gateway', name: 'GP de Madison (Gateway)', location: 'Madison', date: '2026-06-07', circuit: 'Oval', status: 'upcoming' },
      { id: 'road-america-indy', name: 'GP de Road America', location: 'Road America', date: '2026-06-21', circuit: 'Misto', status: 'upcoming' },
      { id: 'mid-ohio', name: 'GP de Mid-Ohio', location: 'Mid-Ohio', date: '2026-07-05', circuit: 'Misto', status: 'upcoming' },
      { id: 'nashville', name: 'GP de Nashville', location: 'Nashville', date: '2026-07-19', circuit: 'Circuito de Rua', status: 'upcoming' },
      { id: 'portland', name: 'GP de Portland', location: 'Portland', date: '2026-08-09', circuit: 'Misto', status: 'upcoming' },
      { id: 'markham', name: 'GP de Markham', location: 'Markham', date: '2026-08-16', circuit: 'Misto', status: 'upcoming' },
      { id: 'washington', name: 'GP de Washington, D.C.', location: 'Washington, D.C.', date: '2026-08-23', circuit: 'Circuito de Rua', status: 'upcoming' },
      { id: 'milwaukee-1', name: 'GP de Milwaukee (Corrida 1)', location: 'Milwaukee', date: '2026-08-29', circuit: 'Oval', status: 'upcoming' },
      { id: 'milwaukee-2', name: 'GP de Milwaukee (Corrida 2)', location: 'Milwaukee', date: '2026-08-30', circuit: 'Oval', status: 'upcoming' },
      { id: 'laguna-seca-indy', name: 'GP de Laguna Seca', location: 'Laguna Seca', date: '2026-09-06', circuit: 'Misto', status: 'upcoming' },
    ],
    standings: {
      drivers: [
        { position: 1, name: 'Kyle Kirkwood', points: 156, team: 'Andretti Global' },
        { position: 2, name: 'Álex Palou', points: 154, team: 'Chip Ganassi Racing' },
        { position: 3, name: 'Christian Lundgaard', points: 121, team: 'Arrow McLaren' },
        { position: 4, name: 'David Malukas', points: 116, team: 'Team Penske' },
        { position: 5, name: 'Josef Newgarden', points: 113, team: 'Team Penske' },
      ],
      teams: [
        { position: 1, name: 'Andretti Global', points: 262 },
        { position: 2, name: 'Team Penske', points: 262 },
        { position: 3, name: 'Chip Ganassi Racing', points: 205 },
        { position: 4, name: 'Arrow McLaren', points: 199 },
        { position: 5, name: 'Meyer Shank Racing', points: 117 },
      ]
    }
  }
];
